@startuml


Class Controller.User{
-fullName : String
-email : String
-licenseNumber: String
--
+ getLicenseNumber(): String
+getEmail(): String
+getFullName(): String
+setLicenseNumber(inout licenseNumber: String)
+setFullName(inout fullName: String)

}

Class Controller.Register{
-mFullName: EditText
-mEmail: EditText
-mPassword: EditText
-mLicenseNumber:EditText
-mRegisterBtn: Button
-fAuth: FirebaseAuth
-progressBar: ProgressBar
user : User
--
#onCreate()
}

Class Controller.Login{
-mEmail: EditText
-mPassword: EditText
-mLoginBtn: Button
-mCreateBtn: TextView
-mforgotText: TextView
-progressBar: ProgressBar
-fAuth: FirebaseAuth
--
#onCreate()
}

class Controller.MainActivity{
-nameText: TextView
-emailExtra: String
-mProfile: ImageView
---
#onCreate()
+getStarted()
}

class Controller.UserProfile{
-user: FirebaseUser
-mBack: ImageView
-userID: String
-reference: DatabaseReference
-log: Button
-edit: Button
--
#onCreate()
}

Class Controller.ForgotPassword{
-emailEdit: EditText
-resetBtn: Button
-progressBar:ProgressBar
-auth: FirebaseAuth
--
#onCreate()
-reset()
}

Class Controller.EditProfile{
-user: FirebaseUser
-mBack: ImageView
-userID: String
-reference: DatabaseReference
-update: Button
--
#onCreate()
}

Class Controller.Map{
-searchView: SearchView
-locBtn: ImageView
-mMap: GoogleMap
-locationManager: LocationManager
- REQUEST_LOCATION_PERMISSION: int
-marker: Marker
-locationListener: LocationListener
----
#onCreate(out savedInstanceState: Bundle)
#onStop()
+onRequestPermissionsResult(requestCode:int, permissions:@NonNull String[],grantResults:@NonNull int[])
+onMapReady(googleMap: GoogleMap)
-bitmapDescriptorFromVector(context: Context, vectorResID: int) : BitmapDescriptor


}
Controller.User "1"<--- Controller.Register





package Firebase <<Database>>{

Class FirebaseUser{

}

Class FirebaseAuth{
--
'getEmail()
'sendPasswordResetEmail(in email: String)
'createUserWithEmailAndPassword(in email: String, in password: String)
'signInWithEmailAndPassword(in email: String, in password: String)
}

Class DatabaseReference{

}

}

package GoogleMaps <<Database>>{

}




@enduml